# Generated by Django 4.0.2 on 2022-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('OWNER', 'Owner'), ('REVIEWER', 'Reviewer')], default='REVIEWER', max_length=10)),
                ('permission', models.CharField(choices=[('READ', 'Read'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='READ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('IMPROVMENT', 'Improvment'), ('TASK', 'Task')], default='BUG', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='TODO', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('IOS', 'Ios'), ('ANDROID', 'Android')], default='BACKEND', max_length=10)),
            ],
        ),
    ]
